### ISSUE TITLE
The character is offset upwards (both in inventory and in F5) [Partially Solved now only in F5]

### ISSUE THREAD

**Issue by TheNicolasDeveloper** [OpenCraft-Studios/OpenCraft#3]
**Describe the bug**
The character is offset upwards in the inventory and in the F5

**To Reproduce**
1. Open your inventory or press F5
2. Observe the wrong behaviour

**Expected behavior**
It should not be offset upwards and should be normal

**Screenshots**
![image](https://github.com/user-attachments/assets/4a019ad7-1864-4121-870c-b825ce90d178)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version nCraft 0.0.1

**Comment by cliserkad** [comment]
I was able to build and run this project. Inventory screen seems to be fixed 👍 
F5 mode shows the player model enlarged and floating above ground.

**Comment by TheNicolasDeveloper** [comment]
I forgot to update the issue, I have partially solved the issue by solving the inventory but not the F5!

**Comment by CiroZDP** [comment]
Solved!
