### ISSUE TITLE
Migrate to LWJGL3

### ISSUE THREAD

**Issue by cliserkad** [OpenCraft-Studios/OpenCraft#31]
**Is your feature request related to a problem? Please describe.**
See #26 . LWJGL2 is a legacy version that won't support newer platforms.

**Describe the solution you'd like**
Migrate to LWJGL3 to get updated binaries for arm64 targets. Game behavior should not change.

**Comment by cliserkad** [comment]
Things that still need fixing:  
- Opening inventory (keyboard input routing is weird)
- Building for a specific target OS/architecture

**Comment by cliserkad** [comment]
Building for a specific OS is complete! But macOS doesn't officially support OpenGL :(

**Comment by cliserkad** [comment]
The game is also running on main thread now

**Comment by CiroZDP** [comment]
> Things that still need fixing:
> 
> * Opening inventory (keyboard input routing is weird)
> * Building for a specific target OS/architecture
> * Running game on main thread

That must be indicated in another issue.
