### ISSUE TITLE
I demand ALL of my commits to be reverted or somehow removed

### ISSUE THREAD

**Issue by TheNicolasDeveloper** [OpenCraft-Studios/OpenCraft#32]
Hello,

I demand ALL of my commits to be reverted/removed, otherwise I will proceed with legal action.

Thank you,
Nicolas.

**Comment by TheNicolasDeveloper** [comment]
Including the following commits:
![image](https://github.com/user-attachments/assets/9c825b3f-4efe-4887-b28a-d77d68adbe2f)

![image](https://github.com/user-attachments/assets/6e520e78-32b9-41ff-8caa-a4d9a9466db0)

**Comment by CiroZDP** [comment]
go cry another place. OpenCraft is goat without you! 😀

**Comment by CiroZDP** [comment]
Plus you don't have any "legal" stuff in there.

**Comment by CiroZDP** [comment]
Luck getting laywers!

**Comment by TheNicolasDeveloper** [comment]
You are required by law to remove my data from this repository.

**Comment by CiroZDP** [comment]
nah i'd win
