### ISSUE TITLE
I'm contacting Mojang's legal team

### ISSUE THREAD

**Issue by TheNicolasDeveloper** [OpenCraft-Studios/OpenCraft#33]
This repository is violating Mojang's intellectual property by utilizing modified code from official Minecraft Infdev. I will be contacting Mojang's legal team to inform them of this.

Thank you for your understanding.

**Comment by CiroZDP** [comment]
minecraft infdev didn't have any license or contract to use it. Plus Microsoft ain't answering u. U are time waste.

Thanks for your understanding
